services:
  db:
    image: ankane/pgvector:latest
    environment:
      POSTGRES_DB: kbol_db
      POSTGRES_USER: kbol_user
      POSTGRES_PASSWORD: kbol_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: